document.addEventListener("DOMContentLoaded",()=>{
 const page=location.pathname.split("/").pop()||"index.html";
 const links=[["index.html","Home"],["products.html","Products"],["industries.html","Industries"],["tools.html","Solutions"],["about.html","About Us"],["certifications.html","Resources"],["contact.html","Contact"]];
 const header=document.querySelector("[data-header]");
 if(header)header.innerHTML=`<header class="site-header"><div class="header-signal"><div class="container signal-inner"><span><b></b> Global supply network online</span><span class="signal-contact"><i data-lucide="phone"></i> +1 (800) 123-4567 <i data-lucide="mail"></i> sales@industrive.com</span></div></div><div class="container nav"><a class="brand brand-plate" href="index.html"><span class="brand-mark"><i data-lucide="box"></i></span><span>InduStrive<small>ENGINEERING EXCELLENCE</small></span></a><nav class="main-nav" data-nav>${links.map(([h,l],i)=>`<a class="${page===h?"active":""}" href="${h}"><em>0${i+1}</em>${l}</a>`).join("")}</nav><div class="header-actions"><a class="header-search" href="products.html" aria-label="Search products"><i data-lucide="search"></i></a><a class="button quote-button" href="rfq.html"><span>Start an RFQ</span><i data-lucide="arrow-up-right"></i></a></div><button class="menu" data-menu aria-label="Open navigation"><i data-lucide="menu"></i></button></div></header>`;
 const footer=document.querySelector("[data-footer]");
 if(footer)footer.innerHTML=`<footer><div class="container footer-grid"><div><a class="brand" href="index.html"><span class="brand-mark"><i data-lucide="box"></i></span><span>InduStrive<small style="color:#8fa3b3">ENGINEERING EXCELLENCE</small></span></a><p>Precision engineered. Performance delivered.</p></div><div><h3>Quick Links</h3><a href="index.html">Home</a><a href="products.html">Products</a><a href="industries.html">Industries</a></div><div><h3>Our Products</h3><a href="product.html">Hydraulic Pumps</a><a href="products.html">Pneumatic Systems</a><a href="products.html">Valves & Fittings</a></div><div><h3>Resources</h3><a href="certifications.html">Certifications</a><a href="tools.html">AI Tools</a><a href="about.html">About Us</a></div><div><h3>Connect</h3><p>+1 (800) 123-4567<br>sales@industrive.com<br>Houston, TX</p></div></div><div class="container footer-bottom">&copy; <span data-year></span> InduStrive. All rights reserved.</div></footer>`;
 window.lucide?.createIcons();
 document.querySelector("[data-menu]")?.addEventListener("click",()=>document.querySelector("[data-nav]").classList.toggle("open"));
 const search=document.querySelector("[data-search]");search?.addEventListener("input",()=>document.querySelectorAll("[data-search-item]").forEach(x=>x.classList.toggle("item-hidden",!x.textContent.toLowerCase().includes(search.value.toLowerCase()))));
 document.querySelectorAll("[data-demo-form]").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();toast("Thank you. Our engineering team will contact you.");form.reset()}));
 document.querySelectorAll("img").forEach(img=>{if(!img.alt)img.alt="InduStrive industrial engineering solution";img.loading="lazy";img.addEventListener("error",()=>img.src="assets/industrial-hero.png",{once:true})});
 document.querySelectorAll("[data-year]").forEach(x=>x.textContent=new Date().getFullYear());
 function toast(msg){const t=document.querySelector("[data-toast]");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
});
